### ISSUE TITLE
Quick Status Check

### ISSUE THREAD

**Issue by MilanFox** [huang-julien/nuxt-applicationinsights#2]
Hey @huang-julien,

Thanks for your work here!
I got here through an issue on the "old" Nuxt 2 solution.
Just dropping a quick note to check in on the project's status.
Is it considered finished, or are there ongoing updates in the pipeline?

I saw the blog post from Alex Lichter about how complex this is, so really trying not to sound pushy here ;)
Just wanted to find out if I can use this already.

Thanks!
Milan

**Comment by huang-julien** [comment]
Hey @MilanFox ! First thanks for looking at this package 😄 !

It is indeed still in progress, i was busy last few weeks but still plan on working on this package this week. 

In the meantime, i'm trying to get in touch with microsoft to review this package. I'll work again on this package this week but  I have a lot of custom implementation on a project at work so (as we stated with Alex), it kinda takes a lot of time to figure out how to optimize some things (and to make it generic enough). I plan to use this package next week to accelerate bug finding and improvements.


0.1 provides a very basic implementation of server side application insights + client application insights

I think it SHOULD be usable but you will probably have some workaround to do. Feel free to open issues on this repo ! All suggestions are welcome !

**Comment by MilanFox** [comment]
Thanks for your reply, keep up the good work!
I will keep an eye on this repo - no pressure though!

In the meantime MS seems to have published a new documentation on the OpenTelemetry API, so I will see if that gets me anywhere:
https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=nodejs

**Comment by huang-julien** [comment]
Thank you ! 
Yes i'm keeping an eye on OpenTelemetry, I'll probably migrate nitro-applicationinsights to it once applicationinsights reach 3.0.
