### ISSUE TITLE
Initialization failure of AppInsights with RuntimeConfig

### ISSUE THREAD

**Issue by julien1619** [huang-julien/nuxt-applicationinsights#68]
With the last version, if you provide a connection string to the module, Application Insights will fail to initialize.

<img width="832" alt="Capture d’écran 2024-06-07 à 15 22 03" src="https://github.com/huang-julien/nuxt-applicationinsights/assets/1506744/a424abc4-8e44-40d1-bd4b-5ab1cdc19552">

The config provided to AppInsights is a Proxy and not a raw object, and AppInsights tries to set its own observer on the object and it fails. One way to fix it would be to use `toRaw`:

```ts
config: toRaw(runtimeConfig.public).applicationinsights ?? {}
```

**Comment by huang-julien** [comment]
damn, i probably forgot to add it back while refactoring. Thanks for the issue !
