### ISSUE TITLE
No Performance metrix in Application Insight

### ISSUE THREAD

**Issue by StijnAvdL** [huang-julien/nuxt-applicationinsights#77]
Hey, 

First thanks for maintaining this project! 

We have added `nuxt-applicationinsights` in our project and if we look at the Application Insights we see a **Application map** which tells us that the connection is made correctly. But all the metrix in **Performance** and **Failures** stay empty. Our setup is the follwing:

- nuxt: 3.5.3
- SSR: true

```
modules: ['nuxt-applicationinsights'],
runtimeConfig: {
    public: {
      applicationinsights: {
        connectionString: 'InstrumentationKey=xxxxx;IngestionEndpoint=xxxxx;LiveEndpoint=xxxx;ApplicationId=xxxxx'
      }
    }
  },
  ```
Are we missing something here with the setup? 

Thanks in advance!

**Comment by huang-julien** [comment]
Hello :wave: Thanks for the issue report. 

Your config seems ok. I'll make a patch release for https://github.com/huang-julien/nuxt-applicationinsights/issues/72. But it seems like you don't have this issue. 

Without a minimal reproduction, i won't be able to tell what's the exact issue.

**Comment by StijnAvdL** [comment]
Thanks for letting me know that my setup is atleast correct.
